name: qsij-quantum-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - pip:
    - jupyterlab>=4.0.0
    - ipywidgets>=8.0.0
    - plotly>=5.0.0
    - seaborn>=0.11.0
    - ipympl
    - quantumsim-edu